sudo: false
language: node_js
node_js: [4]
env:
  global: [CXX=g++-4.8]

addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-4.8, g++-4.8]

cache:
  directories: [bower_components, node_modules]

before_install:
  - echo 'LogLevel=quiet' >> ~/.ssh/config
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - mkdir -p bower_components node_modules
  - npm install -g bower grunt-cli

install:
  - npm install && bower install

script:
  - ls -lah

notifications:
  email: false
