sudo: false
language: php
php: [5.6]

addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-4.8, g++-4.8, tar]

matrix:
  fast_finish: true

cache:
  directories: [bower_components, node_modules, drush_make, ~/.composer/vendor, ~/.drush, ~/.nvm]

env:
  global:
    - CXX=g++-4.8

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - echo 'LogLevel=quiet' >> ~/.ssh/config
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - git config --global user.email "ci@toila.net" &&
    git config --global user.name "CI" &&
    composer global require -q drush/drush:^7.0 &&
    drush --version &&
    npm install -g bower grunt-cli

before_script:
  - git clone -q $BUILD_URL build &&
    git clone -q $MAKE_URL --branch=$MAKE_BRANCH make &&
    # Debug
    cat make/build.make &&
    git clone -q ${ACCOUNTS_URL} accounts &&
    git clone -q ${UI_URL} ui &&
    mkdir -p ${TRAVIS_BUILD_DIR}/drush_make && 
    CACHE_PREFIX=${TRAVIS_BUILD_DIR}/drush_make &&
    export CACHE_PREFIX

script:
  # Make the base Drupal source code
  - cd ${TRAVIS_BUILD_DIR} &&
    drush make -q --concurrency=4 ${TRAVIS_BUILD_DIR}/make/build.make drupal &&
    ls -lah drupal/profiles/gocatalyze &&
    cd drupal/profiles/gocatalyze/vendor &&
    composer install --prefer-dist &&
    cd ${TRAVIS_BUILD_DIR}
    tar -czf ${BUILD_DRUPAL} drupal
