language: node_js
node_js: [4.0.0]
env:
  global:
    - MYV=${TRAVIS_BRANCH}
    - FILE=build-${TRAVIS_BRANCH}-${TRAVIS_TAG}.tar.gz

install:
  - source vars.bash
  - npm install -g npm@2.14.2

before_script:
  - pwd
  - echo ${FOO} ${BAR} ${MYV} ${TRAVIS_TAG}
  - echo ${FILE/-./.}
  - which node
  - which npm
  - which gem
  - which ruby
  - node --version
  - npm --version

script:
  - npm install

after_success:
  - which docker
