language: node_js
node_js: [4]
env:
  global:
    - CXX=g++-4.8

install:
  - source vars.bash

before_script:
  - npm install -g bower
  - node --version
  - npm --version
  - bower --version

script:
  - npm install && bower install
