language: php
php: [5.6]

install:
  - echo 'LogLevel=quiet' >> ~/.ssh/config
  - BUILD=build-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}.tar.gz
  - BRANCH=TravisCI-${TRAVIS_BRANCH}
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - git config --global user.email "thehongtt@gmail.com"
  - git config --global user.name "Andy Truong"
  - git clone -q $BUILD_URL build
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:^7.0

script:
  - drush make -q --concurrency=4 drupal-org.make drupal-code
  - tar -czf $BUILD ./drupal-code/
  - cd build
  - git checkout --orphan ${BRANCH}
  - git rm --cached -r *
  - rm -rf *
  - mv ../$BUILD ./
  - ls -lah
  - git add $BUILD
  - git commit -m "Add $BUILD"

after_success:
  - git push --force origin ${BRANCH}:builds

notifications: { email: false }
