language: node_js
node_js: [4.0.0]
env:
  global:
    - MYV=${TRAVIS_BRANCH}
    - FILE=build-${TRAVIS_BRANCH}-${TRAVIS_TAG}.tar.gz

install:
  - source vars.bash

before_script:
  - npm install -g bower
  - node --version
  - npm --version
  - bower --version

script:
  - npm install && bower install
