  # Commit the build
  - cd ${TRAVIS_BUILD_DIR}/build &&
    git checkout --orphan ${BRANCH} && 
    git rm --cached -r * &&
    rm -rf *
    
  - cd ${TRAVIS_BUILD_DIR}/build
  - mv ${TRAVIS_BUILD_DIR}/${BUILD_DRUPAL} ./
  - mv ${TRAVIS_BUILD_DIR}/${BUILD_ACCOUNTS} ./
  - mv ${TRAVIS_BUILD_DIR}/${BUILD_UI} ./
  - git add ${BUILD_DRUPAL}
  - git commit -m "Add ${BUILD_DRUPAL}"
  - git add ${BUILD_UI}
  - git commit -m "Add ${BUILD_UI}"
  - git add ${BUILD_ACCOUNTS}
  - git commit -m "Add ${BUILD_ACCOUNTS}"
