language: node_js
node_js: [4.0.0]
env:
  global:
    - MYV=${TRAVIS_BRANCH}
    - FILE=build-${TRAVIS_BRANCH}-${TRAVIS_TAG}.tar.gz

install:
  - source vars.bash
  - npm install -g npm@2.14.2
  - npm install -g bower grunt-cli

before_script:
  - which node && which npm && which gem && which ruby && which docker
  - node --version
  - npm --version
  - bower --version

script:
  - npm install && bower install
