sudo: false
language: node_js
node_js: [4]
env:
  global: [CXX=g++-4.8]

addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-4.8, g++-4.8]

cache:
  directories: [bower_components, node_modules]

before_install:
  - echo 'LogLevel=quiet' >> ~/.ssh/config
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - git clone ${UI_URL} ui --branch=deploy
  - mkdir -p bower_components node_modules
  - cd ui
  - ln -s ../bower_components ./
  - ln -s ../node_modules ./
  - npm install -g bower grunt-cli &&
    gem install sass &&
    gem install compass &&
    gem install guard-livereload

install:
  - npm install -q && 
    bower install -q &&
    grunt set-env:testing &&
    grunt build -q

script:
  - cd ${TRAVIS_BUILD_DIR}/ui
  - rm -rf .git .sass-cache .tmp

notifications:
  email: false
