language: php
php: [5.6]

install:
  - BUILD=build-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}.tar.gz
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - git clone -q $BUILD_URL build
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:^7.0

script:
  - drush make drupal-org.make drupal-code

notifications: { email: false }

after_success:
  - tar -cvzf $BUILD ./drupal-code/
  - mv $BUILD build/
  - cd build && git checkout -b builds
  - cd build && git add $BUILD
  - cd build && git commit -m "Add $BUILD"
  - cd build && git push origin 
