sudo: false
language: node_js
node_js: [4]
env:
  global: [CXX=g++-4.8]

addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-4.8, g++-4.8]

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - ls -lah
  - npm install -g bower

install:
  - npm install && 
    bower install

script:
  - ls -lah
