language: node_js
node_js: [4.1]

env:
  global:
    - FILE_UI=ui-${TRAVIS_TAG}.tar.gz
    - BUILD_UI=${FILE_UI/-./.}

install:
  - echo 'LogLevel=quiet' >> ~/.ssh/config
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - npm install -g bower grunt-cli

before_script:
  - git clone ${UI_URL} ui

script:
  # Make the UI
  - cd ${TRAVIS_BUILD_DIR}/ui
  - rm -rf .git
  - npm install && \
    bower install -q && \
    grunt set-env:testing && \
    grunt build

after_failure:
  - gem install gist
  - gist ${TRAVIS_BUILD_DIR}/ui/npm-debug.log

notifications:
  email: false
