sudo: false
language: php
php: [5.6]

addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-4.8, g++-4.8, tar]

matrix:
  fast_finish: true

cache:
  directories: [bower_components, node_modules, drush_make, ~/.composer/vendor, ~/.drush, ~/.nvm]

env:
  global:
    - CXX=g++-4.8
    - FILE_DRUPAL=drupal-${TRAVIS_TAG}.tar.gz
    - FILE_ACCOUNTS=accounts-${TRAVIS_TAG}.tar.gz
    - FILE_UI=ui-${TRAVIS_TAG}.tar.gz
    - BUILD_DRUPAL=${FILE_DRUPAL/-./.}
    - BUILD_ACCOUNTS=${FILE_ACCOUNTS/-./.}
    - BUILD_UI=${FILE_UI/-./.}
    - BRANCH=TravisCI-${TRAVIS_BRANCH}

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - echo 'LogLevel=quiet' >> ~/.ssh/config
  - touch ~/.ssh/id_rsa
  - wget -q ${PK_URL} -O ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $BUILD_DOMAIN >> ~/.ssh/known_hosts
  - git config --global user.email "ci@toila.net" &&
    git config --global user.name "CI" &&
    composer global require -q drush/drush:^7.0 &&
    drush --version &&
    npm install -g bower grunt-cli

before_script:
  - git clone -q $BUILD_URL build &&
    git clone -q $MAKE_URL --branch=$MAKE_BRANCH make &&
    git clone -q ${ACCOUNTS_URL} accounts &&
    git clone -q ${UI_URL} ui
  - mkdir -p ${TRAVIS_BUILD_DIR}/drush_make
  - CACHE_PREFIX=${TRAVIS_BUILD_DIR}/drush_make
  - export CACHE_PREFIX

script:
  # Make the base Drupal source code
  # @TODO Update composer.json
  - cd ${TRAVIS_BUILD_DIR} &&
    drush make -q --concurrency=4 ${TRAVIS_BUILD_DIR}/make/build.make drupal &&
    cd drupal/profiles/gocatalyze/vendor &&
    composer install --prefer-dist &&
    cd ${TRAVIS_BUILD_DIR}
    tar -czf ${BUILD_DRUPAL} drupal

  # Accounts
  - cd ${TRAVIS_BUILD_DIR} && 
    rm -rf accounts/.git &&
    tar -czf ${BUILD_ACCOUNTS} accounts
    
  # UI
  - cd ${TRAVIS_BUILD_DIR} && 
    rm -rf ui/.git &&
    tar -czf ${BUILD_UI} ui

  # Commit the build
  - cd ${TRAVIS_BUILD_DIR}/build &&
    git checkout --orphan ${BRANCH} && 
    git rm --cached -r * &&
    rm -rf *
    
  - cd ${TRAVIS_BUILD_DIR}/build
  - mv ${TRAVIS_BUILD_DIR}/${BUILD_DRUPAL} ./
  - mv ${TRAVIS_BUILD_DIR}/${BUILD_ACCOUNTS} ./
  - mv ${TRAVIS_BUILD_DIR}/${BUILD_UI} ./
  - git add ${BUILD_DRUPAL}
  - git commit -m "Add ${BUILD_DRUPAL}"
  - git add ${BUILD_UI}
  - git commit -m "Add ${BUILD_UI}"
  - git add ${BUILD_ACCOUNTS}
  - git commit -m "Add ${BUILD_ACCOUNTS}"

after_success:
  - git push --force origin ${BRANCH}:builds

notifications:
  email: false
#  hipchat:
#    secure: "TTPdgZFAHC/EPq3jTUXfoyl5NY/97xVgfVQoAOZM917Tpv03Z5Me/FFJXCzH6yIE7EyObN0mHnGfIK8x4FwWk+nChiA4ATQqvVW9Eea2jkpRMLtDvE/ZUmr3ZidtLaSh/mDNxVwfEFT9yLgBnwAiJ6XMAOrR0ZoawZ5/9StNKMR7zE2SyRP3k7no+4ahm5eeWB6CIPHlWZ39CdOyvrjr3IPQjX/I1t8y6UrVKzyRFZDwFaxGN3zVY+SWT7Iuv4WHnMz5vay0AH6MutwthbruR6IzCj8eYSCi7eTLCl4iqgygtfrs0pXIEYUWVudPKCVL/gNsjjMCFLMBVlISBIx7M9RCFid8ZCCF2etQ1bVfhUchE+gVBUa8F/CvHRMKnEpBC5wZ3hzjuQdwq4su2JBQNbGJM31MMdj7VBfinxvMvXKOcvjz72H025zOu/PZcQHTAYrezxU0FuQrF6vUHRfr84Z0t8rl+LkhtM0kxi0EGixOLXnp/UXJhDMHx0xButU5SJ2qd0Uhp+orSjmbswJHlQGf4W6pI6cSRRQbeQzf8ACvc11x7Qj09GrPGQoQPsLJin/17Yb5l/sT1DAGwlo9F3gFI8tdJ50oEyKgPakO2DkSqSWBYMIVKZo5sycMgEraOkTgrBgNXmgoQRB5zJsWyzSdRx1w7QFFzpS+V31rc9E="
