language: php
php: [5.6]
env:
  global:
    - MYV=${TRAVIS_BRANCH}

install:
  - source vars.bash

script:
  - pwd
  - echo ${FOO} ${BAR} ${MYV} ${TRAVIS_TAG}
  - echo ${build-${TRAVIS_BRANCH}-${TRAVIS_TAG}.tar.gz/../.}
  - which node
  - node --version
  - which npm
  - which gem
  - which ruby
